--- 
- name: start mysql
  service:
    name: mysqld
    state: started

- name: restart mysql
  service:
    name: mysqld
    state: restarted

- name: restart iptables
  service:
    name: iptables
    state: restarted
