---
- name: Install php-fpm and deps
  yum: 
   name: "{{ item }}" 
   state: present
  loop: "{{ packages }}"


- name: Disable default pool
  command: mkdir /etc/php-fpm.d/www.disabled &&  mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled 

- name: Copy php-fpm configuration
  template: 
   src: wordpress.conf 
   dest: /etc/php-fpm.d/
  notify: restart php-fpm
